# Generated by Django 3.0.6 on 2020-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
