# Generated by Django 3.0.6 on 2020-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
