# Generated by Django 3.0.6 on 2020-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('audiofile', models.FileField(upload_to='musics/')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='videofile',
        ),
    ]
