# Generated by Django 3.0.6 on 2020-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200520_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='videofile',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
