# Generated by Django 3.0.6 on 2020-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200520_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='youtube',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
