# Generated by Django 3.0.6 on 2020-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_media_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='', upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
